name: Deploy site to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Output Directory
        run: mkdir -p public

      - name: Convert Markdown to HTML
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/data" \
            -u "$(id -u):$(id -g)" \
            pandoc/core:3.5 \
            README.md -o public/index.html --standalone \
            --include-in-header=head.html \
            --metadata title="Muxing Li"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: muxing.info